<<<<<<< HEAD
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
=======
title: MTF studyt 
description: Bookmark this to keep an eye on my project updates!


remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme 
>>>>>>> c40d55a8dd1957c9cf336762579831e99059bf9e
